services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: udp_client

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: udp_server

